# fly.toml app configuration file generated for white-lake-6612 on 2023-11-09T14:09:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "white-lake-6612"
primary_region = "waw"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python quotes/manage.py migrate"

[env]
  PORT = "8000"
  SECRET_KEY = "django-insecure-3my*kaap-5hkyv^htlh2k_0sp67(xj-px%(xk@18o152f_wpcy"

  DATABASE_NAME ="ccepjvxl"
  DATABASE_USER = "ccepjvxl"
  DATABASE_PASSWORD = "PNvMQLLd6WFhy5BGtlL8BDz53dAEWH0_"
  DATABASE_HOST = "snuffleupagus.db.elephantsql.com"
  DATABASE_PORT = 5432

  EMAIL_HOST = "smtp.meta.ua"
  EMAIL_PORT = 465
  EMAIL_HOST_USER = "i_ishchenko@meta.ua"
  EMAIL_HOST_PASSWORD = "1q2w3e5Q"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
